wave_forecast:
  target: dev
  outputs:
    dev:
      type: dremio
      software_host: dremio
      port: 9047
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
      use_ssl: false

      # Write to object storage (MinIO via Dremio source)
      object_storage_source: "lakehouse-minio"
      object_storage_path: "bronze"

      # Connection settings
      threads: 4

    prod:
      type: dremio
      software_host: dremio
      port: 9047
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
      use_ssl: false
      object_storage_source: "lakehouse-minio"
      object_storage_path: "bronze"
      threads: 8
